version: "3.7"

services:
    # image project
    app:
        container_name: subscription-app
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - subscription

    # nginx
    nginx:
        container_name: subscription-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - subscription

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: subscription-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - subscription

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: subscription-phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_ARBITRARY: 1
            PMA_VERBOSE: "Subscription"
            PMA_HOST: "${DB_HOST}"
            PMA_PORT: "${DB_PORT}"
            PMA_USER: "${DB_USERNAME}"
            PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: "20M"
        ports:
            - "8084:80"
        volumes:
            - .docker/phpmyadmin/data/sessions:/sessions
        networks:
            - subscription

    # redis
    redis:
        container_name: subscription-redis
        image: redis:latest
        networks:
            - subscription

networks:
    subscription:
        driver: bridge
